### ISSUE TITLE
Detect UTF-32

### ISSUE THREAD

**Issue by alugowski** [sigpwned/chardet4j#43]
Currently only UTF-8 and UTF-16 are detected, with the explanation that the JVM does not support UTF-32.

It would be useful to at least detect UTF-32, even if reading it is not possible.
- Enables an app to emit a useful error message.
- Some applications only need detection

`decode()` can throw an IOException if the input is UTF-32.

See:

https://github.com/sigpwned/chardet4j/blob/2737978f2cfc69cadb933f7cca54b4e75f9e16ef/src/main/java/com/sigpwned/chardet4j/ByteOrderMark.java#L27-L50

**Comment by sigpwned** [comment]
Good point. We can do more here. Let me poke around this week and see what I see.

**Comment by sigpwned** [comment]
I've added support for detecting UTF-32 (among others), and added some methods to help with detection. 

If you'd like to decode, then this should work:

```java
try (Reader chars=Chardet.decode(bytes, StandardCharsets.UTF_8)) {
    // Process chars here
} catch(UnsupportedCharsetException e) {
    // The charset was detected, but is not supported by current JVM. There are a
    // few ways this is typically handled:
    // 
    // - Propagate as an IOException, since the content cannot be decoded properly
    // - Ignore the error and use a default charset
}
``` 

If you just want to detect, one of these should do:

```
// Throws an UnsupportedCharsetException if the charset is not supported by JVM
Optional<Charset> maybeCharset = Chardet.detect(bytes, declaredEncoding);

// Never throws
Optional<String> maybeCharsetName = Chardet.detectName(bytes, declaredEncoding);
```

The README is updated as well, which provides further context.

I've released these changes under version 75.1.1. It takes Maven a minute to make new artifacts available, in my experience, but they should be ready by evening at the latest, I should think.

Thanks again for the suggestion! Please don't hesitate to open new issues with any more suggestions or questions!

**Comment by alugowski** [comment]
Amazing! thank you so much!

**Comment by alugowski** [comment]
Shouldn't it be `UnsupportedEncodingException` and not `UnsupportedCharsetException`? UTF-32 and UTF-8 both use the same charset (Unicode), don't they?

**Comment by sigpwned** [comment]
I love good questions. :)

Unfortunately, Java's handling of encodings and charsets is a bit muddled, IMO.

A charset is a logical set of characters. UTF-1, UTF-7, UTF-8, UTF-16, and UTF-32 are all different encodings for the Unicode character set. You're spot on there. However, Java puts all of these in the [`Charset`](https://docs.oracle.com/javase/8/docs/api/index.html?java/nio/charset/Charset.html) class, alongside things like US-ASCII and ISO-8859-1, which are legitimately different character sets. To make things even more confusing, the `char` type is explicitly required to be a UTF-16 code unit, per [the spec](https://docs.oracle.com/javase/tutorial/java/nutsandbolts/datatypes.html), so Java's view of the character encoding and charset world is really just things that convert to and from UTF-16 code units in memory.

So while Java's *support* for character encodings and character sets is outstanding, its *model* for same is, well, not so good.

At the end of the day, I opted for `UnsupportedCharsetException` for a few reasons, in rough order of importance:

1. It's unchecked, so I can start using it without changing the method signatures of existing code to maintain backwards compatability. `UnsupportedEncodingException` is checked, which would have broken backwards compatibility.
2. It was natural the way I wrote the code. I pass around `Charset` objects internally, so I see `UnsupportedEncodingException`. If I were passing around names to things like `InputStreamReader`, then I would be seeing a lot more of `UnsupportedEncodingException` instead.
3. It's just newer. New code seems to be using `UnsupportedEncodingException`, for better or for worse. And since Java's model for character encodings and charsets is a bit fluid anyway, I didn't get too worried about it.

Hopefully that gives a bit of a window into the logic!
